cargo-features = ["panic-immediate-abort"]

[package]
name = "fastcount"
version = "0.2.1"
description = "an incredibly fast, incredibly useless counter"
license = "Apache-2.0"
repository = "https://github.com/CallMeAlphabet/fastcount"
edition = "2024"

[dependencies]
clihelp = "0.1"

[[bin]]
name = "fastcount"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "immediate-abort"
strip = true
split-debuginfo = "off"
